In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
df=pd.read_csv("Myntra_Fashion.csv",low_memory=False)
df.head(10)

,URL,Product_id,BrandName,Category,Individual_category,category_by_Gender,Description,DiscountPrice (in Rs),OriginalPrice (in Rs),DiscountOffer,SizeOption,Ratings,Reviews
0,https://www.myntra.com/jeans/roadster/roadster...,2296012,Roadster,Bottom Wear,jeans,Men,roadster men navy blue slim fit mid rise clean...,824.0,1499.0,45% OFF,"28, 30, 32, 34, 36",3.9,999.0
1,https://www.myntra.com/track-pants/locomotive/...,13780156,LOCOMOTIVE,Bottom Wear,track-pants,Men,locomotive men black white solid slim fit tra...,517.0,1149.0,55% OFF,"S, M, L, XL",4.0,999.0
2,https://www.myntra.com/shirts/roadster/roadste...,11895958,Roadster,Topwear,shirts,Men,roadster men navy white black geometric print...,629.0,1399.0,55% OFF,"38, 40, 42, 44, 46, 48",4.3,999.0
3,https://www.myntra.com/shapewear/zivame/zivame...,4335679,Zivame,Lingerie & Sleep Wear,shapewear,Women,zivame women black saree shapewear zi3023core0...,893.0,1295.0,31% OFF,"S, M, L, XL, XXL",4.2,999.0
4,https://www.myntra.com/tshirts/roadster/roadst...,11690882,Roadster,Western,tshirts,Women,roadster women white solid v neck pure cotton ...,NaN,599.0,35% OFF,"XS, S, M, L, XL",4.2,999.0
5,https://www.myntra.com/tops/mast--harbour/mast...,2490950,Mast & Harbour,Western,tops,Women,mast harbour women yellow solid tank top,NaN,599.0,40% OFF,"XS, S, M, L, XL",4.4,999.0
6,https://www.myntra.com/trousers/highlander/hig...,6744434,HIGHLANDER,Bottom Wear,trousers,Men,highlander men olive green slim fit solid regu...,599.0,1499.0,60% OFF,"30, 32, 34, 36",3.9,998.0
7,https://www.myntra.com/tops/mayra/mayra-pink-e...,8439415,Mayra,Western,tops,Women,mayra pink embroidered a line pure cotton top,NaN,1395.0,58% OFF,"S, M, L, XL",3.7,998.0
8,https://www.myntra.com/tshirts/roadster/roadst...,17381394,Roadster,Western,tshirts,Women,roadster women pack of 2 solid t shirts,NaN,1098.0,NaN,"XS, S, M, L, XL",4.3,997.0
9,https://www.myntra.com/jeans/herenow/herenow-m...,2359257,HERE&NOW,Bottom Wear,jeans,Men,herenow men blue slim fit mid rise clean look ...,NaN,2749.0,NaN,"28, 30, 32, 34, 36",3.5,996.0

In [7]:
#dimensions rows and columns
df.shape

(526564, 13)

In [8]:
#column names
df.columns

Index(['URL', 'Product_id', 'BrandName', 'Category', 'Individual_category',
       'category_by_Gender', 'Description', 'DiscountPrice (in Rs)',
       'OriginalPrice (in Rs)', 'DiscountOffer', 'SizeOption', 'Ratings',
       'Reviews'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526564 entries, 0 to 526563
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   URL                    526564 non-null  object
 1   Product_id             526564 non-null  int64
 2   BrandName              526564 non-null  object
 3   Category               526564 non-null  object
 4   Individual_category    526564 non-null  object
 5   category_by_Gender     526564 non-null  object
 6   Description            526564 non-null  object
 7   DiscountPrice (in Rs)  333406 non-null  float64
 8   OriginalPrice (in Rs)  526564 non-null  float64
 9   DiscountOffer          452258 non-null  object
 10  SizeOption             526564 non-null  object
 11  Ratings                190412 non-null  float64
 12  Reviews                190412 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 52.2+ MB

In [10]:
#check missing values discountprice,offer,ratings and reviews
df.isnull().sum()

URL                           0
Product_id                    0
BrandName                     0
Category                      0
Individual_category           0
category_by_Gender            0
Description                   0
DiscountPrice (in Rs)    193158
OriginalPrice (in Rs)         0
DiscountOffer             74306
SizeOption                    0
Ratings                  336152
Reviews                  336152
dtype: int64

In [4]:
#check duplicate rows
df.duplicated().sum()
#if duplicates exists
df.drop_duplicates(inplace=True)
#verify
df.duplicated().sum()
#no duplicates

np.int64(0)

In [5]:
#check data types
df.dtypes

URL                       object
Product_id                 int64
BrandName                 object
Category                  object
Individual_category       object
category_by_Gender        object
Description               object
DiscountPrice (in Rs)    float64
OriginalPrice (in Rs)    float64
DiscountOffer             object
SizeOption                object
Ratings                  float64
Reviews                  float64
dtype: object

In [6]:
#phase 3
#long column names incovenient so make it short
df.rename(columns={
    "DiscountPrice (in Rs)": "DiscountPrice",
    "OriginalPrice (in Rs)": "OriginalPrice",
    "category_by_Gender": "Gender",
    "Individual_category": "SubCategory"
}, inplace=True)

In [7]:
#verify whether names are shortened
df.columns

Index(['URL', 'Product_id', 'BrandName', 'Category', 'SubCategory', 'Gender',
       'Description', 'DiscountPrice', 'OriginalPrice', 'DiscountOffer',
       'SizeOption', 'Ratings', 'Reviews'],
      dtype='object')

In [9]:
#Clean text columns
#Remove unwanted spaces
df["BrandName"] = df["BrandName"].str.strip()
df["Category"] = df["Category"].str.strip()
df["SubCategory"] = df["SubCategory"].str.strip()

In [10]:
#Standardize text
df["BrandName"] = df["BrandName"].str.title()

In [11]:
#check missing ratings
df["Ratings"].isnull().sum()

np.int64(336152)

In [12]:
#fill with median values
median_rating = df["Ratings"].median()

df["Ratings"] = df["Ratings"].fillna(median_rating)

In [13]:
#verify
df["Ratings"].isnull().sum()

np.int64(0)

In [14]:
#fill missing reviews
df["Reviews"].isnull().sum()

np.int64(336152)

In [16]:
#fill null with 0
df["Reviews"] = df["Reviews"].fillna(0)

In [17]:
#verify
df["Reviews"].isnull().sum()

np.int64(0)

In [18]:
#convert review data type float to integer
df["Reviews"]=df["Reviews"].astype(int)

In [20]:
##verify data type of review
df["Reviews"].dtypes

dtype('int64')

In [22]:
#check discount price missing values
df["DiscountPrice"].isnull().sum()

np.int64(193158)

In [23]:
#fill with original price
df["DiscountPrice"] = df["DiscountPrice"].fillna(df["OriginalPrice"])

In [24]:
#verify
df["DiscountPrice"].isnull().sum()

np.int64(0)

In [25]:
#check missing values of discount offer
df["DiscountOffer"].isnull().sum()

np.int64(74306)

In [26]:
#fill missing values with no discount
df["DiscountOffer"] = df["DiscountOffer"].fillna("No Discount")

In [27]:
#verify
df["DiscountOffer"].isnull().sum()

np.int64(0)

In [28]:
#check for impossible values
df.describe()

,Product_id,DiscountPrice,OriginalPrice,Ratings,Reviews
count,5.265640e+05,526564.000000,526564.000000,526564.000000,526564.000000
mean,1.506939e+07,1528.493978,2414.068615,4.161992,22.416641
std,3.225710e+06,1305.689078,1916.962914,0.301418,81.253156
min,2.739900e+04,99.000000,99.000000,1.000000,0.000000
25%,1.388053e+07,749.000000,1299.000000,4.200000,0.000000
50%,1.597106e+07,1199.000000,1999.000000,4.200000,0.000000
75%,1.734741e+07,1905.000000,2899.000000,4.200000,9.000000
max,1.846435e+07,90000.000000,90000.000000,5.000000,999.000000

In [29]:
#Phase 4
#create new columns
#Discount Amount
df["DiscountAmount"] = df["OriginalPrice"] -df["DiscountPrice"]

In [30]:
#Discount Percentage
df["DiscountPercentage"] = ((df["DiscountPrice"]/ df["OriginalPrice"]) * 100)

In [31]:
#Revenue score
df["ReviewScore"] = (df["DiscountPrice"] * df["Reviews"])

In [32]:
#Review new columns Discountamount,Discounpercentage and reviewscore
df.head()

,URL,Product_id,BrandName,Category,SubCategory,Gender,Description,DiscountPrice,OriginalPrice,DiscountOffer,SizeOption,Ratings,Reviews,DiscountAmount,DiscountPercentage,ReviewScore
0,https://www.myntra.com/jeans/roadster/roadster...,2296012,Roadster,Bottom Wear,jeans,Men,roadster men navy blue slim fit mid rise clean...,824.0,1499.0,45% OFF,"28, 30, 32, 34, 36",3.9,999,675.0,54.969980,823176.0
1,https://www.myntra.com/track-pants/locomotive/...,13780156,Locomotive,Bottom Wear,track-pants,Men,locomotive men black white solid slim fit tra...,517.0,1149.0,55% OFF,"S, M, L, XL",4.0,999,632.0,44.995648,516483.0
2,https://www.myntra.com/shirts/roadster/roadste...,11895958,Roadster,Topwear,shirts,Men,roadster men navy white black geometric print...,629.0,1399.0,55% OFF,"38, 40, 42, 44, 46, 48",4.3,999,770.0,44.960686,628371.0
3,https://www.myntra.com/shapewear/zivame/zivame...,4335679,Zivame,Lingerie & Sleep Wear,shapewear,Women,zivame women black saree shapewear zi3023core0...,893.0,1295.0,31% OFF,"S, M, L, XL, XXL",4.2,999,402.0,68.957529,892107.0
4,https://www.myntra.com/tshirts/roadster/roadst...,11690882,Roadster,Western,tshirts,Women,roadster women white solid v neck pure cotton ...,599.0,599.0,35% OFF,"XS, S, M, L, XL",4.2,999,0.0,100.000000,598401.0

In [33]:
#Saved cleaned data
#This completes data cleaning
df.to_csv("Myntra_Cleaned.csv",index=False)

In [38]:
#If your file is a CSV or Excel file, use pandas and #sqlalchemy to push it straight to MySQL:
#import pandas as pd
#from sqlalchemy import create_engine
import pandas as pd
from sqlalchemy import create_engine

# 1. Read your file from the folder
df = pd.read_csv("Myntra_Cleaned.csv")  # Use pd.read_excel() if it's an Excel file
df
# 2. Connect to MySQL (Replace with your username, password, and host)
# 3. Create the new database
#with engine.connect() as conn:
   # conn.execute("CREATE DATABASE IF NOT EXISTS myntra_db;")
# 4. Reconnect to the new database and load the data
Engine=create_engine('mysql+pymysql://root:pass123@localhost:3306/myntra_db')
df.to_sql(name='myntra_fashion',con=Engine,if_exists='replace',index=False)

526564